export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS';
export const FETCH_AUTHORS_FAILURE = 'FETCH_AUTHORS_FAILURE';
export const CREATE_AUTHORS_SUCCESS = 'CREATE_AUTHORS_SUCCESS';
export const CREATE_AUTHORS_FAILURE = 'CREATE_AUTHORS_FAILURE';
